# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9c82a494e4c6476d30b41ab3f0ce8fb9"
application_url = "https://example.com"
embedded = true
name = "ropstem-cart-transform"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_cart_transforms,write_metaobject_definitions,write_metaobjects,write_products"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[webhooks]
api_version = "2026-10"

[build]
automatically_update_urls_on_dev = true
