# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "387c74e985dcdfd86b2ec16b9a4799ea"
application_url = "https://example.com"
embedded = true
name = "ropstem-cart"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_metaobjects,write_metaobject_definitions,write_cart_transforms"

[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
