api_version = "2026-07"

[[extensions]]
name = "t:name"
handle = "cart-transformer-rop"
type = "function"
uid = "708c4f54-7680-3c02-020c-b369333498456d974fc3"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/cart_transform_run.graphql"
  export = "cart-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
